name: CI for go-web-app

on: 
    pull_request:
        branches:
        - main
        paths-ignore: 
        - 'README.MD'
        - 'helm/**'

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go v1.22
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.5'

      - name: Build
        run: go build -o go-web-app

      - name: Test
        run: go test ./...