on:
    workflow_dispatch
jobs:
    checkout_repos:
        runs-on: self-hosted

        steps:
        - name: Checkout current repo
          uses: actions/checkout@v4
          with:
            path: GO-WEB-APP

        - name: Setup SSH
          run: |
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            echo "${{secrets.REPO_B_PRIVATE_KEY}}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa && chmod 600 ~/.ssh/known_hosts
            ssh-keyscan github.com >> ~/.ssh/known_hosts

        - name: Checkout RepoB
          run: |
            if [ ! -d "Example-Voting-app" ]; then
              git clone --branch git-testing git@github.com:Sreeju1992-kodekloud/Example-Voting-app.git Example-Voting-app
            else
              cd Example-Voting-app
              git fetch
              if ! git merge FETCH_HEAD; then
                 echo "Merge conflict detected. Please resolve manually"
                 exit 1
              fi
            fi

        - name: Get the current path
          run: pwd

        - name: Run Migrate.sh script
          working-directory: GO-WEB-APP/scripts
          run: |
            pwd
            chmod +x migrate.sh
            ./migrate.sh inventory

        - name: Compare and push the files
          working-directory: Example-Voting-app
          run: |
            if [ -n "$(git status --porcelain)" ]; then
               echo "Changes detected in the repository. Preparing to commit and push."
               echo "changes_detected=true" >> $GITHUB_ENV
               git config --global user.name "GitHub Actions"
               git config --global user.email "actions@github.com"
               git add -A
               git commit -m "Auto-commit: Changes detected and committed automatically"
               git push origin $(git rev-parse --abbrev-ref HEAD)
            else
               echo "No changes detected"
               echo "changes_detected=false" >> $GITHUB_ENV
            fi

        - name: Action if no changes detected
          if: env.changes_detected == 'false'
          run: |
            echo "No action needed"

        - name: Trigger Workflow in repository B
          if: env.changes_detected == 'true'
          run: |
            curl -L -f \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPOSITORY_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Sreeju1992-kodekloud/Example-Voting-app/dispatches \
            -d '{"event_type":"dispatch-event", "client_payload": {"message": "Hello from the trigger repository!"}}'


    