on:
    workflow_dispatch
jobs:
    checkout_repos:
        runs-on: self-hosted

        steps:
        - name: Checkout current repo
          uses: actions/checkout@v4
          with:
            path: GO-WEB-APP

        - name: Setup SSH
          run: |
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            echo "${{secrets.REPO_B_PRIVATE_KEY}}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa && chmod 600 ~/.ssh/known_hosts
            ssh-keyscan github.com >> ~/.ssh/known_hosts

        - name: Checkout RepoB
          run: |
            if [ ! -d "Example-Voting-app" ]; then
              git clone git@github.com:Sreeju1992/Example-Voting-app.git Example-Voting-app
            else
              cd Example-Voting-app
              git fetch
              if ! git merge FETCH_HEAD; then
                 echo "Merge conflict detected. Please resolve manually"
                 exit 1
              fi
            fi

        - name: Get the current path
          run: pwd

        - name: Run Migrate.sh script
          working-directory: GO-WEB-APP/scripts
          run: |
            pwd
            chmod +x migrate.sh
            ./migrate.sh inventory

        - name: Compare and push the files
          working-directory: Example-Voting-app
          run: |
            if [ -n "$(git status --porcelain)" ]; then
               echo "Changes detected in the repository. Preparing to commit and push."
               git config --global user.name "GitHub Actions"
               git config --global user.email "actions@github.com"
               git add -A
               git commit -m "Auto-commit: Changes detected and committed automatically"
               git push origin $(git rev-parse --abbrev-ref HEAD)
            else
               echo "No changes detected"
            fi


    