name: CI for go-web-app

on: workflow_dispatch
jobs:
    build:
      runs-on: self-hosted

      steps:
      - name: Remove old repo
        run: |
           rm -rf go-web-app Example-Voting-app

      - name: Checkout repository go-web-app
        uses: actions/checkout@v4
        with:
          path: go-web-app

      - name: Checkout repository Example-Voting-app
        uses: actions/checkout@v4
        with:
            path: Example-Voting-app

      - name: test
        run: echo "test"